transform:
  outputs:
    dev:
      type: postgres
      host: raw_db_serv
      port: 5432
      user: user
      pass: secret
      dbname: raw_db
      schema: public
      threads: 1
    local:
      type: postgres
      host: localhost
      port: 5433
      user: user
      pass: secret
      dbname: raw_db
      schema: public
      threads: 1
  target: dev