services:
  db_serv:
    build:
      context: .
      dockerfile: dockerfile_db
    container_name: db_con
    ports:
      - "5433:5432"
    networks:
      - ed_network
    volumes:
      - ed_raw_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U user -d db

  airflow_db_serv:
    image: postgres:17
    networks:
      - ed_network
    environment:
      - POSTGRES_USER=airflow_db
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=airflow
    healthcheck:
      test: pg_isready -U airflow_db -d airflow

  airflow_init_serv:
    image: apache/airflow:2.9.3
    depends_on:
      - db_serv
      - airflow_db_serv
    networks:
      - ed_network
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow_db:secret@airflow_db_serv/airflow
    command: >
      bash -c "airflow db init &&
               airflow users create --username user --password secret --firstname John --lastname Doe --role Admin --email admin@example.com"

  airflow_webserver_serv:
    build:
      context: .
      dockerfile: dockerfile_airflow
    user: root
    depends_on:
      airflow_init_serv:
        condition: service_completed_successfully
    networks:
      - ed_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./src/airflow/dags:/opt/airflow/dags
      - ./src/loading:/opt/airflow/loading
      - ./src/transform:/opt/airflow/transform
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow_db:secret@airflow_db_serv/airflow
      - AIRFLOW_CONN_DESTINATION_POSTGRES=postgres://user:secret@db_serv:5432/db
      - AIRFLOW__CORE__FERNET_KEY=58nUcS7V9h-FPsbjeRqQV7Dzj416uaBANEuF10thTnU=
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=Europe/Berlin
      - AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE=Europe/Berlin
      - AIRFLOW__WEBSERVER__DEFAULT_USER_USERNAME=user
      - AIRFLOW__WEBSERVER__DEFAULT_USER_PASSWORD=secret
      - AIRFLOW_WWW_USER_USERNAME=user
      - AIRFLOW_WWW_USER_PASSWORD=secret
      - AIRFLOW__WEBSERVER__SECRET_KEY=secret
    ports:
      - "8080:8080"
    command: webserver

  airflow_scheduler_serv:
    build:
      context: .
      dockerfile: dockerfile_airflow
    user: root
    depends_on:
      airflow_init_serv:
        condition: service_completed_successfully
    networks:
      - ed_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./src/airflow/dags:/opt/airflow/dags
      - ./src/loading:/opt/airflow/loading
      - ./src/transform:/opt/airflow/transform
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow_db:secret@airflow_db_serv/airflow
      - AIRFLOW_CONN_DESTINATION_POSTGRES=postgres://user:secret@db_serv:5432/db
      - AIRFLOW__CORE__FERNET_KEY=58nUcS7V9h-FPsbjeRqQV7Dzj416uaBANEuF10thTnU=
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=Europe/Berlin
      - AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE=Europe/Berlin
      - AIRFLOW_WWW_USER_USERNAME=user
      - AIRFLOW__WEBSERVER__SECRET_KEY=secret
      - AIRFLOW_WWW_USER_PASSWORD=secret
    command: scheduler

  airflow_initial_trigger_serv:
    image: apache/airflow:2.9.3
    depends_on:
      - airflow_scheduler_serv
    networks:
      - ed_network
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow_db:secret@airflow_db_serv/airflow
    command: >
      bash -c "
      for i in $(seq 1 30); do
        airflow dags trigger extract_load_and_transform && exit 0;
        sleep 5;
      done;
      exit 1;
      "

  app_serv:
    build:
      context: .
      dockerfile: Dockerfile_app
    container_name: app_con
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db_serv
      DB_PORT: "5432"
    volumes:
      - ./src:/app/src
    depends_on:
      db_serv:
        condition: service_healthy
    networks:
      - ed_network

networks:
  ed_network:
    name: ed_network
    driver: bridge

volumes:
  ed_raw_data: